// <auto-generated>
// Generated from Native/Box2D/prowl_box2d.h by tools/ccsharp/gen_pb2.py. Do not edit: change the header and regenerate.
// .NET flavor: [LibraryImport] over the real pointers, wrapped so the public signatures match the C flavor exactly.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace Prowl.Native.Box2D
{
  [StructLayout(LayoutKind.Sequential)]
  internal struct PB2BodyMove
  {
    public int bodyIndex;
    public float x;
    public float y;
    public float c;
    public float s;
    public int fellAsleep;
  }

  [StructLayout(LayoutKind.Sequential)]
  internal struct PB2ContactEvent
  {
    public int colliderA;
    public int colliderB;
    public float px;
    public float py;
    public float nx;
    public float ny;
    public float impulse;
    public int flags;
    public int bodyA;
    public int bodyB;
  }

  [StructLayout(LayoutKind.Sequential)]
  internal struct PB2SensorEvent
  {
    public int sensorCollider;
    public int visitorCollider;
    public int flags;
  }

  [StructLayout(LayoutKind.Sequential)]
  internal struct PB2StepInfo
  {
    public int moveCount;
    public int contactCount;
    public int contactBeginCount;
    public int sensorCount;
    public int awakeBodyCount;
    public int jointEventCount;
    public nint moves;
    public nint contacts;
    public nint sensors;
    public nint joints;
  }

  [StructLayout(LayoutKind.Sequential)]
  internal struct PB2TransformSet
  {
    public uint body;
    public float x;
    public float y;
    public float angle;
    public int mode;
  }

  [StructLayout(LayoutKind.Sequential)]
  internal struct PB2RayHit
  {
    public int collider;
    public int body;
    public float px;
    public float py;
    public float nx;
    public float ny;
    public float fraction;
  }

  [StructLayout(LayoutKind.Sequential)]
  internal unsafe struct PB2JointDef
  {
    public uint bodyA;
    public uint bodyB;
    public int jointIndex;
    public int type;
    public uint flags;
    public float ax;
    public float ay;
    public float aAngle;
    public float bx;
    public float by;
    public float bAngle;
    public float forceThreshold;
    public float torqueThreshold;
    public fixed float p[PB2.JointParams];
  }

  internal static unsafe partial class PB2
  {
    private const string Lib = "prowl_box2d";
    public const int AbiVersion = 2;
    public const int LayerCount = 32;
    public const int EventBegin = 1;
    public const int EventEnd = 2;
    public const int JointDistance = 0;
    public const int JointRevolute = 1;
    public const int JointPrismatic = 2;
    public const int JointWheel = 3;
    public const int JointWeld = 4;
    public const int JointMotor = 5;
    public const int JointFilter = 6;
    public const uint JfSpring = 1u;
    public const uint JfLimit = 2u;
    public const uint JfMotor = 4u;
    public const uint JfCollideConnected = 8u;
    public const int JointParams = 12;
    public const int BodyStatic = 0;
    public const int BodyKinematic = 1;
    public const int BodyDynamic = 2;
    public const uint BfBullet = 1u;
    public const uint BfNoSleep = 2u;
    public const uint BfLockX = 4u;
    public const uint BfLockY = 8u;
    public const uint BfLockRot = 16u;
    public const uint BfDisabled = 32u;
    public const uint SfSensor = 1u;

    [LibraryImport(Lib, EntryPoint = "pb2_abi")] private static partial void RawAbi(int* out16);
    public static void Abi(int[] out16)
    {
        fixed (int* p_out16 = out16)
        {
            RawAbi(p_out16);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_world_create")] public static partial void WorldCreate(float gravityX, float gravityY, int workerCount);
    [LibraryImport(Lib, EntryPoint = "pb2_world_destroy")] public static partial void WorldDestroy();
    [LibraryImport(Lib, EntryPoint = "pb2_world_set_gravity")] public static partial void WorldSetGravity(float x, float y);
    [LibraryImport(Lib, EntryPoint = "pb2_world_set_layer_matrix")] private static partial void RawWorldSetLayerMatrix(uint* rows32);
    public static void WorldSetLayerMatrix(uint[] rows32)
    {
        fixed (uint* p_rows32 = rows32)
        {
            RawWorldSetLayerMatrix(p_rows32);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_step")] private static partial void RawStep(float dt, int subSteps, PB2StepInfo* info);
    public static void Step(float dt, int subSteps, ref PB2StepInfo info)
    {
        fixed (PB2StepInfo* p_info = &info)
        {
            RawStep(dt, subSteps, p_info);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_bodies_set_transforms")] private static partial void RawBodiesSetTransforms(PB2TransformSet* sets, int count, float dt);
    public static void BodiesSetTransforms(List<PB2TransformSet> sets, int count, float dt)
    {
        fixed (PB2TransformSet* p_sets = System.Runtime.InteropServices.CollectionsMarshal.AsSpan(sets))
        {
            RawBodiesSetTransforms(p_sets, count, dt);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_body_create")] public static partial uint BodyCreate(int type, float x, float y, float angle, int bodyIndex, float gravityScale, float linearDamping, float angularDamping, uint flags);
    [LibraryImport(Lib, EntryPoint = "pb2_body_destroy")] public static partial void BodyDestroy(uint body);
    [LibraryImport(Lib, EntryPoint = "pb2_body_set_transform")] public static partial void BodySetTransform(uint body, float x, float y, float angle);
    [LibraryImport(Lib, EntryPoint = "pb2_body_set_type")] public static partial void BodySetType(uint body, int type);
    [LibraryImport(Lib, EntryPoint = "pb2_body_set_flags")] public static partial void BodySetFlags(uint body, uint flags);
    [LibraryImport(Lib, EntryPoint = "pb2_body_set_damping")] public static partial void BodySetDamping(uint body, float linear, float angular);
    [LibraryImport(Lib, EntryPoint = "pb2_body_set_gravity_scale")] public static partial void BodySetGravityScale(uint body, float scale);
    [LibraryImport(Lib, EntryPoint = "pb2_body_set_velocity")] public static partial void BodySetVelocity(uint body, float vx, float vy, float angularVelocity);
    [LibraryImport(Lib, EntryPoint = "pb2_body_set_mass")] public static partial void BodySetMass(uint body, float mass);
    [LibraryImport(Lib, EntryPoint = "pb2_body_set_awake")] public static partial void BodySetAwake(uint body, int awake);
    [LibraryImport(Lib, EntryPoint = "pb2_body_apply_force")] public static partial void BodyApplyForce(uint body, float fx, float fy, int hasPoint, float px, float py);
    [LibraryImport(Lib, EntryPoint = "pb2_body_apply_impulse")] public static partial void BodyApplyImpulse(uint body, float ix, float iy, int hasPoint, float px, float py);
    [LibraryImport(Lib, EntryPoint = "pb2_body_apply_torque")] public static partial void BodyApplyTorque(uint body, float torque, int asImpulse);
    [LibraryImport(Lib, EntryPoint = "pb2_body_get_state")] private static partial void RawBodyGetState(uint body, float* out10);
    public static void BodyGetState(uint body, float[] out10)
    {
        fixed (float* p_out10 = out10)
        {
            RawBodyGetState(body, p_out10);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_shape_create_circle")] public static partial uint ShapeCreateCircle(uint body, int colliderIndex, int layer, float cx, float cy, float radius, float density, float friction, float restitution, uint flags);
    [LibraryImport(Lib, EntryPoint = "pb2_shape_create_box")] public static partial uint ShapeCreateBox(uint body, int colliderIndex, int layer, float halfW, float halfH, float ox, float oy, float angle, float cornerRadius, float density, float friction, float restitution, uint flags);
    [LibraryImport(Lib, EntryPoint = "pb2_shape_create_capsule")] public static partial uint ShapeCreateCapsule(uint body, int colliderIndex, int layer, float x1, float y1, float x2, float y2, float radius, float density, float friction, float restitution, uint flags);
    [LibraryImport(Lib, EntryPoint = "pb2_shape_create_polygon")] private static partial uint RawShapeCreatePolygon(uint body, int colliderIndex, int layer, float* xy, int pointCount, float radius, float density, float friction, float restitution, uint flags);
    public static uint ShapeCreatePolygon(uint body, int colliderIndex, int layer, float[] xy, int pointCount, float radius, float density, float friction, float restitution, uint flags)
    {
        fixed (float* p_xy = xy)
        {
            return RawShapeCreatePolygon(body, colliderIndex, layer, p_xy, pointCount, radius, density, friction, restitution, flags);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_segments_create")] private static partial int RawSegmentsCreate(uint body, int colliderIndex, int layer, float* xy, int pointCount, int isLoop, float friction, float restitution, uint* outShapes);
    public static int SegmentsCreate(uint body, int colliderIndex, int layer, float[] xy, int pointCount, int isLoop, float friction, float restitution, uint[] outShapes)
    {
        fixed (float* p_xy = xy)
        {
            fixed (uint* p_outShapes = outShapes)
            {
                return RawSegmentsCreate(body, colliderIndex, layer, p_xy, pointCount, isLoop, friction, restitution, p_outShapes);
            }
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_chain_create")] private static partial uint RawChainCreate(uint body, int colliderIndex, int layer, float* xy, int pointCount, int isLoop, float friction, float restitution);
    public static uint ChainCreate(uint body, int colliderIndex, int layer, float[] xy, int pointCount, int isLoop, float friction, float restitution)
    {
        fixed (float* p_xy = xy)
        {
            return RawChainCreate(body, colliderIndex, layer, p_xy, pointCount, isLoop, friction, restitution);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_shape_destroy")] public static partial void ShapeDestroy(uint shape);
    [LibraryImport(Lib, EntryPoint = "pb2_chain_destroy")] public static partial void ChainDestroy(uint chain);
    [LibraryImport(Lib, EntryPoint = "pb2_shape_set_material")] public static partial void ShapeSetMaterial(uint shape, float friction, float restitution);
    [LibraryImport(Lib, EntryPoint = "pb2_shape_set_density")] public static partial void ShapeSetDensity(uint shape, float density);
    [LibraryImport(Lib, EntryPoint = "pb2_joint_create")] private static partial uint RawJointCreate(PB2JointDef* def);
    public static uint JointCreate(ref PB2JointDef def)
    {
        fixed (PB2JointDef* p_def = &def)
        {
            return RawJointCreate(p_def);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_joint_destroy")] public static partial void JointDestroy(uint joint);
    [LibraryImport(Lib, EntryPoint = "pb2_joint_is_valid")] public static partial int JointIsValid(uint joint);
    [LibraryImport(Lib, EntryPoint = "pb2_joint_apply")] private static partial void RawJointApply(uint joint, PB2JointDef* def);
    public static void JointApply(uint joint, ref PB2JointDef def)
    {
        fixed (PB2JointDef* p_def = &def)
        {
            RawJointApply(joint, p_def);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_joint_get_state")] private static partial void RawJointGetState(uint joint, float* out8);
    public static void JointGetState(uint joint, float[] out8)
    {
        fixed (float* p_out8 = out8)
        {
            RawJointGetState(joint, p_out8);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_raycast")] private static partial int RawRaycast(float ox, float oy, float dx, float dy, float maxDistance, uint layerMask, int hitSensors, PB2RayHit* @out);
    public static int Raycast(float ox, float oy, float dx, float dy, float maxDistance, uint layerMask, int hitSensors, ref PB2RayHit @out)
    {
        fixed (PB2RayHit* p_out = &@out)
        {
            return RawRaycast(ox, oy, dx, dy, maxDistance, layerMask, hitSensors, p_out);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_raycast_all")] private static partial int RawRaycastAll(float ox, float oy, float dx, float dy, float maxDistance, uint layerMask, int hitSensors, PB2RayHit* @out, int capacity);
    public static int RaycastAll(float ox, float oy, float dx, float dy, float maxDistance, uint layerMask, int hitSensors, List<PB2RayHit> @out, int capacity)
    {
        fixed (PB2RayHit* p_out = System.Runtime.InteropServices.CollectionsMarshal.AsSpan(@out))
        {
            return RawRaycastAll(ox, oy, dx, dy, maxDistance, layerMask, hitSensors, p_out, capacity);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_overlap_point")] private static partial int RawOverlapPoint(float x, float y, uint layerMask, int hitSensors, int* @out, int capacity);
    public static int OverlapPoint(float x, float y, uint layerMask, int hitSensors, int[] @out, int capacity)
    {
        fixed (int* p_out = @out)
        {
            return RawOverlapPoint(x, y, layerMask, hitSensors, p_out, capacity);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_overlap_circle")] private static partial int RawOverlapCircle(float cx, float cy, float radius, uint layerMask, int hitSensors, int* @out, int capacity);
    public static int OverlapCircle(float cx, float cy, float radius, uint layerMask, int hitSensors, int[] @out, int capacity)
    {
        fixed (int* p_out = @out)
        {
            return RawOverlapCircle(cx, cy, radius, layerMask, hitSensors, p_out, capacity);
        }
    }

    [LibraryImport(Lib, EntryPoint = "pb2_overlap_box")] private static partial int RawOverlapBox(float cx, float cy, float halfW, float halfH, float angle, uint layerMask, int hitSensors, int* @out, int capacity);
    public static int OverlapBox(float cx, float cy, float halfW, float halfH, float angle, uint layerMask, int hitSensors, int[] @out, int capacity)
    {
        fixed (int* p_out = @out)
        {
            return RawOverlapBox(cx, cy, halfW, halfH, angle, layerMask, hitSensors, p_out, capacity);
        }
    }

    /// <summary>Throws if the loaded library was built from a different header than these structs: every record size and the ABI version are compared.</summary>
    public static void VerifyAbi()
    {
        int[] abi = new int[16];
        Abi(abi);
        string bad = "";
        if (abi[0] != AbiVersion) bad += "ABI version is " + abi[0] + " natively and " + AbiVersion + " here; ";
        if (abi[1] != System.Runtime.CompilerServices.Unsafe.SizeOf<PB2BodyMove>()) bad += "PB2BodyMove is " + abi[1] + " natively and " + System.Runtime.CompilerServices.Unsafe.SizeOf<PB2BodyMove>() + " here; ";
        if (abi[2] != System.Runtime.CompilerServices.Unsafe.SizeOf<PB2ContactEvent>()) bad += "PB2ContactEvent is " + abi[2] + " natively and " + System.Runtime.CompilerServices.Unsafe.SizeOf<PB2ContactEvent>() + " here; ";
        if (abi[3] != System.Runtime.CompilerServices.Unsafe.SizeOf<PB2SensorEvent>()) bad += "PB2SensorEvent is " + abi[3] + " natively and " + System.Runtime.CompilerServices.Unsafe.SizeOf<PB2SensorEvent>() + " here; ";
        if (abi[4] != System.Runtime.CompilerServices.Unsafe.SizeOf<PB2StepInfo>()) bad += "PB2StepInfo is " + abi[4] + " natively and " + System.Runtime.CompilerServices.Unsafe.SizeOf<PB2StepInfo>() + " here; ";
        if (abi[5] != System.Runtime.CompilerServices.Unsafe.SizeOf<PB2TransformSet>()) bad += "PB2TransformSet is " + abi[5] + " natively and " + System.Runtime.CompilerServices.Unsafe.SizeOf<PB2TransformSet>() + " here; ";
        if (abi[6] != System.Runtime.CompilerServices.Unsafe.SizeOf<PB2RayHit>()) bad += "PB2RayHit is " + abi[6] + " natively and " + System.Runtime.CompilerServices.Unsafe.SizeOf<PB2RayHit>() + " here; ";
        if (abi[7] != IntPtr.Size) bad += "pointer size is " + abi[7] + " natively and " + IntPtr.Size + " here; ";
        if (abi[8] != System.Runtime.CompilerServices.Unsafe.SizeOf<PB2JointDef>()) bad += "PB2JointDef is " + abi[8] + " natively and " + System.Runtime.CompilerServices.Unsafe.SizeOf<PB2JointDef>() + " here; ";
        if (bad.Length > 0) throw new InvalidOperationException("prowl_box2d ABI mismatch: " + bad + "Rebuild Native/Box2D.");
    }


    public static PB2BodyMove StepInfoMoves(ref PB2StepInfo record, int index) => ((PB2BodyMove*)record.moves)[index];
    public static PB2ContactEvent StepInfoContacts(ref PB2StepInfo record, int index) => ((PB2ContactEvent*)record.contacts)[index];
    public static PB2SensorEvent StepInfoSensors(ref PB2StepInfo record, int index) => ((PB2SensorEvent*)record.sensors)[index];
    public static int StepInfoJoints(ref PB2StepInfo record, int index) => ((int*)record.joints)[index];
    public static float JointDefGetP(ref PB2JointDef record, int index) { fixed (PB2JointDef* r = &record) return r->p[index]; }
    public static void JointDefSetP(ref PB2JointDef record, int index, float value) { fixed (PB2JointDef* r = &record) r->p[index] = value; }
  }
}
