#!/usr/bin/env python3
"""prowl2d_so.py -- build libprowl2d.so: the 2D engine as C, in one shared library a Python (ctypes) host can load.

    python3 tools/prowl2d_so.py [-o /tmp/libprowl2d.so] [--no-sdl] [--cc CC] [--keep]
    (or:  python3 build.py so)

What goes in it:

  1. Native/Engine2D/Engine.cs, a flat handle-based facade over Prowl.Core2D (ints and floats only), translated to C together with the engine by CC# (the only
     step that needs .NET: the Roslyn-based translator; the library that comes out has none);
  2. a shim generated from Engine.cs's `public static` signatures: each becomes an exported `p2d_<snake_case>` function (NewNode -> p2d_new_node), so the
     C# and the exports cannot drift apart;
  3. the renderer, Native/Gfx2D, built with -DGFX_SDL, which adds the window (gfx_window_open, gfx_present, and the window's input in gfx_poll_event). All of its
     gfx_* functions are exported as they are: textures, triangles, clip, fonts, events;
  4. Box2D and its shim, statically.

The result needs only libEGL, libGLESv2, libSDL2 and libc at run time. --no-sdl builds the headless renderer (no window): the library then has no libSDL2 dependency.

Build needs: the siblings `python3 build.py deps --ccsharp` clones, `python3 build.py native` (Box2D), a .NET SDK for the translator, and libegl-dev libgles-dev libsdl2-dev.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(HERE, "ccsharp"))
import ccsharp_scan as scan   # noqa: E402
import player_build           # noqa: E402

ENGINE_DIR = os.path.join(ROOT, "Native", "Engine2D")
GFX_DIR = os.path.join(ROOT, "Native", "Gfx2D")
GFX_SOURCES = ["gfx2d.c", "gfx2d_ui.c", "gfx2d_font.c", "gfx2d_font_data.c"]
C_TYPES = {"int": "int", "float": "float", "void": "void"}


def snake(name):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name).lower()


def parse_api(cs_path):
    """The `public static` functions of the Engine class: [(ret, Name, [(type, name), ...])]. Only int, float and void are allowed: this is what a ctypes
    host can call without building anything, so a signature outside that is an error here, not a surprise later."""
    with open(cs_path, encoding="utf-8") as f:
        text = re.sub(r"//[^\n]*", "", f.read())
    api = []
    for m in re.finditer(r"public\s+static\s+(\w+)\s+(\w+)\s*\(([^)]*)\)", text):
        ret, name, params = m.group(1), m.group(2), m.group(3).strip()
        if name == "Main":
            continue
        plist = []
        for p in [x.strip() for x in params.split(",") if x.strip()]:
            parts = p.split()
            if len(parts) != 2 or parts[0] not in C_TYPES:
                sys.exit("prowl2d_so: Engine.%s: parameter '%s' is not 'int x' or 'float x' (the exported API is ints and floats only)" % (name, p))
            plist.append((parts[0], parts[1]))
        if ret not in C_TYPES:
            sys.exit("prowl2d_so: Engine.%s returns %s: only int, float and void are exported" % (name, ret))
        api.append((ret, name, plist))
    if not api:
        sys.exit("prowl2d_so: no public static functions found in %s" % cs_path)
    return api


def exports_c(api):
    lines = ["/* engine_exports.c: GENERATED by tools/prowl2d_so.py from Native/Engine2D/Engine.cs. Do not edit; change Engine.cs and rebuild. */",
             "#define main prowl2d_discarded_main /* the translated entry point is not wanted in a library */",
             '#include "player.c"',
             "#undef main",
             "#define P2D_EXPORT __attribute__((visibility(\"default\")))",
             ""]
    for ret, name, plist in api:
        proto = ", ".join("%s %s" % (C_TYPES[t], n) for t, n in plist) or "void"
        call = "Engine_%s(%s)" % (name, ", ".join(n for _, n in plist))
        body = ("return " + call + ";") if ret != "void" else (call + ";")
        lines.append("P2D_EXPORT %s p2d_%s(%s) { %s }" % (C_TYPES[ret], snake(name), proto, body))
    return "\n".join(lines) + "\n"


def header_h(api):
    lines = ["/* libprowl2d.h: the exported engine API (generated with the library from Native/Engine2D/Engine.cs). The renderer's gfx_* functions are exported too: Native/Gfx2D/gfx2d.h. */",
             "#ifndef LIBPROWL2D_H", "#define LIBPROWL2D_H", ""]
    for ret, name, plist in api:
        proto = ", ".join("%s %s" % (C_TYPES[t], n) for t, n in plist) or "void"
        lines.append("%s p2d_%s(%s);" % (C_TYPES[ret], snake(name), proto))
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def run(cmd, cwd=None):
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if r.returncode != 0:
        print("   $ " + " ".join(cmd))
        print((r.stdout + r.stderr)[-2500:])
        sys.exit("prowl2d_so: failed (%d)" % r.returncode)
    return r


def build_gfx(work, cc, sdl):
    """The renderer's objects (-fPIC, and -DGFX_SDL for the window) in work/gfx."""
    crust = scan.crust_home() if hasattr(scan, "crust_home") else os.path.join(os.path.dirname(ROOT), "crust")
    batch = os.path.join(crust, "examples", "unity_pack")
    if not os.path.exists(os.path.join(batch, "gles3_batch.h")):
        sys.exit("prowl2d_so: crust is not at %s (python3 build.py deps --ccsharp)" % crust)
    gdir = os.path.join(work, "gfx")
    os.makedirs(gdir, exist_ok=True)
    flags = ["-O2", "-ffp-contract=off", "-w", "-fPIC", "-I", GFX_DIR, "-I", batch]
    if sdl:
        flags += ["-DGFX_SDL"] + subprocess.check_output(["sdl2-config", "--cflags"], text=True).split()
    objs = []
    for name in GFX_SOURCES:
        obj = os.path.join(gdir, name[:-2] + ".o")
        run([cc] + flags + ["-c", os.path.join(GFX_DIR, name), "-o", obj])
        objs.append(obj)
    return objs


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--out", default="/tmp/libprowl2d.so", help="the library to write (default /tmp/libprowl2d.so); libprowl2d.h is written beside it")
    ap.add_argument("--no-sdl", action="store_true", help="the headless renderer: no window, no libSDL2")
    ap.add_argument("--cc", default=os.environ.get("CC") or "cc")
    ap.add_argument("--keep", action="store_true", help="keep the work folder (Build/Engine2D): the translated C and the generated shim")
    a = ap.parse_args()
    sdl = not a.no_sdl
    if sdl and not shutil.which("sdl2-config"):
        sys.exit("prowl2d_so: SDL2 is needed for the window (apt install libsdl2-dev), or build the headless library with --no-sdl")

    cs = os.path.join(ENGINE_DIR, "Engine.cs")
    api = parse_api(cs)
    work = os.path.join(ROOT, "Build", "Engine2D")
    shutil.rmtree(work, ignore_errors=True)
    os.makedirs(work)

    native_dir = scan.native_library_dir()
    if native_dir is None:
        sys.exit("prowl2d_so: the Box2D library is not built (python3 build.py native)")

    print("== translating Native/Engine2D/Engine.cs with the 2D runtime (%d exported functions)" % len(api))
    player_build.check_constants()
    c_file, diags, raw = player_build.translate([cs], work, "Engine", True)
    if c_file is None:
        print("\n".join(diags) if diags else raw[-2000:])
        sys.exit("prowl2d_so: the translator refused Engine.cs (see above)")
    print("   %s  (%d lines of C)" % (os.path.relpath(c_file, ROOT), sum(1 for _ in open(c_file))))

    # what the C needs beside it: the shim, the two headers, the native static libraries
    shutil.copy2(c_file, os.path.join(work, "player.c"))
    shutil.copy2(os.path.join(ROOT, "Native", "Box2D", "prowl_box2d.h"), work)
    shutil.copy2(os.path.join(GFX_DIR, "gfx2d.h"), work)
    with open(os.path.join(work, "engine_exports.c"), "w", newline="\n") as f:
        f.write(exports_c(api))

    print("== the renderer (%s)" % ("with the SDL2 window" if sdl else "headless"))
    objs = build_gfx(work, a.cc, sdl)

    b2 = [scan.find_native_lib("libprowl_box2d_static.a"), scan.find_native_lib("libbox2d.a")]
    if None in b2:
        sys.exit("prowl2d_so: libprowl_box2d_static.a / libbox2d.a are missing (python3 build.py native)")

    print("== linking %s" % a.out)
    out = os.path.abspath(a.out)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    cmd = ([a.cc, "-shared", "-fPIC", "-O2", "-ffp-contract=off", "-w", "-I", work, "-o", out, os.path.join(work, "engine_exports.c")] + objs
           + b2 + ["-lEGL", "-lGLESv2"] + (["-lSDL2"] if sdl else []) + ["-lm"])
    run(cmd, cwd=work)
    with open(os.path.join(os.path.dirname(out), "libprowl2d.h"), "w", newline="\n") as f:
        f.write(header_h(api))
    print("   built %s  (%d KiB)%s" % (out, os.path.getsize(out) // 1024, "" if sdl else "  [headless]"))
    if not a.keep:
        pass  # the work folder is small and its translated C is useful when something goes wrong: it is under Build/, which is ignored
    return 0


if __name__ == "__main__":
    sys.exit(main())
